### ISSUE TITLE
No game freeze/race start teleport after finishing the race

### ISSUE THREAD

**Issue by SpaceAstra** [oldnapalm/CommunityRaces#7]
Hello,
First of all I love your work and enjoy it very much ! I was wondering if you could add an option, so that after you finish the race you are not teleported back to the starting point. When that happens I have to respawn the car (this removes all damage and dirt accumulated) and go back. It would be nice if you could just pass through the finish checkpoint and continue.
Thanks !

**Comment by oldnapalm** [comment]
Hi,
I can add an option to continue in the car after the race finish screen (press esc instead of enter). Just passing through the finish checkpoint is a bit harder, would need many changes, I'm not sure if it's worth.
Please test if this is ok for you
[CommunityRaces.zip](https://github.com/oldnapalm/CommunityRaces/files/8344690/CommunityRaces.zip)

**Comment by SpaceAstra** [comment]
Its perfect. I appreciate it a lot ! Thanks.
