### ISSUE TITLE
Artificial intelligence drivers

### ISSUE THREAD

**Issue by erme0330033333** [oldnapalm/CommunityRaces#8]
Hello,

Artificial intelligence drivers go to very different places on a long map and in a long time, is it possible to fix this?

**Comment by oldnapalm** [comment]
Hi.

I couldn't find a fix.

Maybe `IS_NAVMESH_LOADED_IN_AREA` could be used to check if the navmesh is loaded between the ped (or vehicle) position and the destination, and if it's not, call `ADD_NAVMESH_REQUIRED_REGION`.

Also, maybe `TASK_VEHICLE_DRIVE_TO_COORD_LONGRANGE` could be used instead of `TASK_VEHICLE_MISSION_COORS_TARGET`.

**Comment by erme0330033333** [comment]
Thank you for your answer. So where should I type these commands?

**Comment by oldnapalm** [comment]
Instead of https://github.com/oldnapalm/CommunityRaces/blob/d1304ae9c7035d22253b9d9734c153a354e6425a/CommunityRaces.cs#L291

```c#
                if (!Function.Call<bool>(Hash.IS_NAVMESH_LOADED_IN_AREA, riv.Vehicle.Position.X, riv.Vehicle.Position.Y, riv.Vehicle.Position.Z, race.Checkpoints[0].X, race.Checkpoints[0].Y, race.Checkpoints[0].Z))
                    Function.Call<bool>(Hash.ADD_NAVMESH_REQUIRED_REGION, riv.Vehicle.Position.X, riv.Vehicle.Position.Y, World.GetDistance(riv.Vehicle.Position, race.Checkpoints[0]));
                riv.Character.Task.DriveTo(riv.Vehicle, race.Checkpoints[0], 10f, 500f, Rival.MainDrivingStyle);
```

Instead of https://github.com/oldnapalm/CommunityRaces/blob/d1304ae9c7035d22253b9d9734c153a354e6425a/CommunityRaces.cs#L561

```c#
                        if (!Function.Call<bool>(Hash.IS_NAVMESH_LOADED_IN_AREA, tuple.Item1.Vehicle.Position.X, tuple.Item1.Vehicle.Position.Y, tuple.Item1.Vehicle.Position.Z, _currentRace.Checkpoints[tuple.Item2 + 1].X, _currentRace.Checkpoints[tuple.Item2 + 1].Y, _currentRace.Checkpoints[tuple.Item2 + 1].Z))
                            Function.Call<bool>(Hash.ADD_NAVMESH_REQUIRED_REGION, tuple.Item1.Vehicle.Position.X, tuple.Item1.Vehicle.Position.Y, World.GetDistance(tuple.Item1.Vehicle.Position, _currentRace.Checkpoints[tuple.Item2 + 1]));
                        tuple.Item1.Character.Task.DriveTo(tuple.Item1.Vehicle, _currentRace.Checkpoints[tuple.Item2 + 1], 10f, 500f, Rival.MainDrivingStyle);
```

[CommunityRaces.zip](https://github.com/oldnapalm/CommunityRaces/files/12488225/CommunityRaces.zip) (untested)

**Comment by erme0330033333** [comment]
Thank you. I want to get paid help on a subject, how can I reach you? Can you help?

**Comment by oldnapalm** [comment]
You can contact me on Discord https://discord.gg/kw4dAUQUx4

Any luck with the test above?

**Comment by erme0330033333** [comment]
Yes, I tested the file, but after a while the artificial intelligences were scattered around.
